services:
  app:
    build:
      context: ./RPI_Script
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      PI_NAME: dev_pi
      DB_IDS: ids
      DB_TEMPERATURES: temperatures
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB: rpi_db
    command: python main.py -simulate
    restart: no
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpi_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
  website:
    build:
      context: ./rpiapp2
      dockerfile: Dockerfile
      args:
        VITE_PUBLIC_WEBSOCKET_URL: "ws://localhost:8080"
    depends_on:
      websocket:
        condition: service_started
        restart: true
      db:
        condition: service_healthy
        restart: true
    environment:
      VITE_PUBLIC_WEBSOCKET_URL: "ws://localhost:8080"
    restart: unless-stopped
    ports:
      - "80:80"
  websocket:
    build:
      context: ./rpi_websocket
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      WEBSOCKET_PORT: 8080
      DATABASE_READ_USER: root
      DATABASE_READ_PASSWORD: root
      DATABASE_READ_HOST: db
      DATABASE_READ_DATABASE: rpi_db
      TEMPERATURE_TABLE: temperatures
      IDS_TABLE: ids
    ports:
      - "8080:8080"
    restart: unless-stopped
